-- TRAWORLD Premium Products Seed from Myntra

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709506',
  'traworld-40709506-traworld-polypropylene-360-degree-rotation-trolley-bag',
  'TRAWORLD Polypropylene 360-Degree Rotation Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Polypropylene 360-Degree Rotation Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  16669,
  16669,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709506/1.jpg',
  '["/products/traworld/40709506/1.jpg", "/products/traworld/40709506/2.jpg", "/products/traworld/40709506/3.jpg", "/products/traworld/40709506/4.jpg", "/products/traworld/40709506/5.jpg", "/products/traworld/40709506/6.jpg"]'::jsonb,
  '[{"name": "Black", "code": "#1a1a1a", "images": ["/products/traworld/40709506/1.jpg", "/products/traworld/40709506/2.jpg", "/products/traworld/40709506/3.jpg", "/products/traworld/40709506/4.jpg", "/products/traworld/40709506/5.jpg", "/products/traworld/40709506/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Polypropylene 360-Degree Rotation Trolley Bag", "SKU": "TRW-40709506", "Material": "Durable High-Grade Polypropylene / Polycarbonate", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  true,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-polypropylene-360-degree-rotation-trolley-bag/40709506/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709514',
  'traworld-40709514-traworld-polypropylene-360-degree-rotation-trolley-bag',
  'TRAWORLD Polypropylene 360-Degree Rotation Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Polypropylene 360-Degree Rotation Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  12499,
  12499,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709514/1.jpg',
  '["/products/traworld/40709514/1.jpg", "/products/traworld/40709514/2.jpg", "/products/traworld/40709514/3.jpg", "/products/traworld/40709514/4.jpg", "/products/traworld/40709514/5.jpg", "/products/traworld/40709514/6.jpg"]'::jsonb,
  '[{"name": "Black", "code": "#1a1a1a", "images": ["/products/traworld/40709514/1.jpg", "/products/traworld/40709514/2.jpg", "/products/traworld/40709514/3.jpg", "/products/traworld/40709514/4.jpg", "/products/traworld/40709514/5.jpg", "/products/traworld/40709514/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Polypropylene 360-Degree Rotation Trolley Bag", "SKU": "TRW-40709514", "Material": "Durable High-Grade Polypropylene / Polycarbonate", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  true,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-polypropylene-360-degree-rotation-trolley-bag/40709514/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709509',
  'traworld-40709509-traworld-polypropylene-360-degree-rotation-padded-trolley-bag',
  'TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  7549,
  7549,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709509/1.jpg',
  '["/products/traworld/40709509/1.jpg", "/products/traworld/40709509/2.jpg", "/products/traworld/40709509/3.jpg", "/products/traworld/40709509/4.jpg", "/products/traworld/40709509/5.jpg", "/products/traworld/40709509/6.jpg"]'::jsonb,
  '[{"name": "Black", "code": "#1a1a1a", "images": ["/products/traworld/40709509/1.jpg", "/products/traworld/40709509/2.jpg", "/products/traworld/40709509/3.jpg", "/products/traworld/40709509/4.jpg", "/products/traworld/40709509/5.jpg", "/products/traworld/40709509/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag", "SKU": "TRW-40709509", "Material": "Durable High-Grade Polypropylene / Polycarbonate", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  true,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-polypropylene-360-degree-rotation-padded-trolley-bag/40709509/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709520',
  'traworld-40709520-traworld-polypropylene-360-degree-rotation-padded-trolley-bag',
  'TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  7549,
  7549,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709520/1.jpg',
  '["/products/traworld/40709520/1.jpg", "/products/traworld/40709520/2.jpg", "/products/traworld/40709520/3.jpg", "/products/traworld/40709520/4.jpg", "/products/traworld/40709520/5.jpg", "/products/traworld/40709520/6.jpg"]'::jsonb,
  '[{"name": "Green", "code": "#1a1a1a", "images": ["/products/traworld/40709520/1.jpg", "/products/traworld/40709520/2.jpg", "/products/traworld/40709520/3.jpg", "/products/traworld/40709520/4.jpg", "/products/traworld/40709520/5.jpg", "/products/traworld/40709520/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag", "SKU": "TRW-40709520", "Material": "Durable High-Grade Polypropylene / Polycarbonate", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  true,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-polypropylene-360-degree-rotation-padded-trolley-bag/40709520/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709508',
  'traworld-40709508-traworld-set-of-2-360-degree-rotation-padded-trolley-bag',
  'TRAWORLD Set Of 2 360-Degree Rotation Padded Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Set Of 2 360-Degree Rotation Padded Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  16669,
  16669,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709508/1.jpg',
  '["/products/traworld/40709508/1.jpg", "/products/traworld/40709508/2.jpg", "/products/traworld/40709508/3.jpg", "/products/traworld/40709508/4.jpg", "/products/traworld/40709508/5.jpg", "/products/traworld/40709508/6.jpg"]'::jsonb,
  '[{"name": "Black", "code": "#1a1a1a", "images": ["/products/traworld/40709508/1.jpg", "/products/traworld/40709508/2.jpg", "/products/traworld/40709508/3.jpg", "/products/traworld/40709508/4.jpg", "/products/traworld/40709508/5.jpg", "/products/traworld/40709508/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Set Of 2 360-Degree Rotation Padded Trolley Bag", "SKU": "TRW-40709508", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-set-of-2-360-degree-rotation-padded-trolley-bag/40709508/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709525',
  'traworld-40709525-traworld-polypropylene-360-degree-rotation-padded-trolley-bag',
  'TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  12499,
  12499,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709525/1.jpg',
  '["/products/traworld/40709525/1.jpg", "/products/traworld/40709525/2.jpg", "/products/traworld/40709525/3.jpg", "/products/traworld/40709525/4.jpg", "/products/traworld/40709525/5.jpg", "/products/traworld/40709525/6.jpg"]'::jsonb,
  '[{"name": "Black", "code": "#1a1a1a", "images": ["/products/traworld/40709525/1.jpg", "/products/traworld/40709525/2.jpg", "/products/traworld/40709525/3.jpg", "/products/traworld/40709525/4.jpg", "/products/traworld/40709525/5.jpg", "/products/traworld/40709525/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag", "SKU": "TRW-40709525", "Material": "Durable High-Grade Polypropylene / Polycarbonate", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-polypropylene-360-degree-rotation-padded-trolley-bag/40709525/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709532',
  'traworld-40709532-traworld-set-of-3-360-degree-rotation-padded-trolley-bag',
  'TRAWORLD Set Of 3 360-Degree Rotation Padded Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Set Of 3 360-Degree Rotation Padded Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  24996,
  24996,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709532/1.jpg',
  '["/products/traworld/40709532/1.jpg", "/products/traworld/40709532/2.jpg", "/products/traworld/40709532/3.jpg", "/products/traworld/40709532/4.jpg", "/products/traworld/40709532/5.jpg", "/products/traworld/40709532/6.jpg"]'::jsonb,
  '[{"name": "Blue", "code": "#1a1a1a", "images": ["/products/traworld/40709532/1.jpg", "/products/traworld/40709532/2.jpg", "/products/traworld/40709532/3.jpg", "/products/traworld/40709532/4.jpg", "/products/traworld/40709532/5.jpg", "/products/traworld/40709532/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Set Of 3 360-Degree Rotation Padded Trolley Bag", "SKU": "TRW-40709532", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-set-of-3-360-degree-rotation-padded-trolley-bag/40709532/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709504',
  'traworld-40709504-traworld-set-of-2-360-degree-rotation-padded-trolley-bag',
  'TRAWORLD Set Of 2 360-Degree Rotation Padded Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Set Of 2 360-Degree Rotation Padded Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  16669,
  16669,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709504/1.jpg',
  '["/products/traworld/40709504/1.jpg", "/products/traworld/40709504/2.jpg", "/products/traworld/40709504/3.jpg", "/products/traworld/40709504/4.jpg", "/products/traworld/40709504/5.jpg", "/products/traworld/40709504/6.jpg"]'::jsonb,
  '[{"name": "Blue", "code": "#1a1a1a", "images": ["/products/traworld/40709504/1.jpg", "/products/traworld/40709504/2.jpg", "/products/traworld/40709504/3.jpg", "/products/traworld/40709504/4.jpg", "/products/traworld/40709504/5.jpg", "/products/traworld/40709504/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Set Of 2 360-Degree Rotation Padded Trolley Bag", "SKU": "TRW-40709504", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-set-of-2-360-degree-rotation-padded-trolley-bag/40709504/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709536',
  'traworld-40709536-traworld-polypropylene-360-degree-rotation-padded-trolley-bag',
  'TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  7549,
  7549,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709536/1.jpg',
  '["/products/traworld/40709536/1.jpg", "/products/traworld/40709536/2.jpg", "/products/traworld/40709536/3.jpg", "/products/traworld/40709536/4.jpg", "/products/traworld/40709536/5.jpg", "/products/traworld/40709536/6.jpg"]'::jsonb,
  '[{"name": "Blue", "code": "#1a1a1a", "images": ["/products/traworld/40709536/1.jpg", "/products/traworld/40709536/2.jpg", "/products/traworld/40709536/3.jpg", "/products/traworld/40709536/4.jpg", "/products/traworld/40709536/5.jpg", "/products/traworld/40709536/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag", "SKU": "TRW-40709536", "Material": "Durable High-Grade Polypropylene / Polycarbonate", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-polypropylene-360-degree-rotation-padded-trolley-bag/40709536/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709552',
  'traworld-40709552-traworld-polypropylene-360-degree-rotation-padded-trolley-bag',
  'TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  12499,
  12499,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709552/1.jpg',
  '["/products/traworld/40709552/1.jpg", "/products/traworld/40709552/2.jpg", "/products/traworld/40709552/3.jpg", "/products/traworld/40709552/4.jpg", "/products/traworld/40709552/5.jpg", "/products/traworld/40709552/6.jpg"]'::jsonb,
  '[{"name": "Brown", "code": "#1a1a1a", "images": ["/products/traworld/40709552/1.jpg", "/products/traworld/40709552/2.jpg", "/products/traworld/40709552/3.jpg", "/products/traworld/40709552/4.jpg", "/products/traworld/40709552/5.jpg", "/products/traworld/40709552/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag", "SKU": "TRW-40709552", "Material": "Durable High-Grade Polypropylene / Polycarbonate", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-polypropylene-360-degree-rotation-padded-trolley-bag/40709552/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709505',
  'traworld-40709505-traworld-360-degree-rotation-padded-trolley-bag',
  'TRAWORLD 360-Degree Rotation Padded Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD 360-Degree Rotation Padded Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  9599,
  9599,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709505/1.jpg',
  '["/products/traworld/40709505/1.jpg", "/products/traworld/40709505/2.jpg", "/products/traworld/40709505/3.jpg", "/products/traworld/40709505/4.jpg", "/products/traworld/40709505/5.jpg", "/products/traworld/40709505/6.jpg"]'::jsonb,
  '[{"name": "Black", "code": "#1a1a1a", "images": ["/products/traworld/40709505/1.jpg", "/products/traworld/40709505/2.jpg", "/products/traworld/40709505/3.jpg", "/products/traworld/40709505/4.jpg", "/products/traworld/40709505/5.jpg", "/products/traworld/40709505/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD 360-Degree Rotation Padded Trolley Bag", "SKU": "TRW-40709505", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-360-degree-rotation-padded-trolley-bag/40709505/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709545',
  'traworld-40709545-traworld-polypropylene-360-degree-rotation-padded-trolley-bag',
  'TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  24996,
  24996,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709545/1.jpg',
  '["/products/traworld/40709545/1.jpg", "/products/traworld/40709545/2.jpg", "/products/traworld/40709545/3.jpg", "/products/traworld/40709545/4.jpg", "/products/traworld/40709545/5.jpg", "/products/traworld/40709545/6.jpg"]'::jsonb,
  '[{"name": "Blue", "code": "#1a1a1a", "images": ["/products/traworld/40709545/1.jpg", "/products/traworld/40709545/2.jpg", "/products/traworld/40709545/3.jpg", "/products/traworld/40709545/4.jpg", "/products/traworld/40709545/5.jpg", "/products/traworld/40709545/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag", "SKU": "TRW-40709545", "Material": "Durable High-Grade Polypropylene / Polycarbonate", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-polypropylene-360-degree-rotation-padded-trolley-bag/40709545/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709518',
  'traworld-40709518-traworld-polypropylene-360-degree-rotation-padded-trolley-bag',
  'TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  16669,
  16669,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709518/1.jpg',
  '["/products/traworld/40709518/1.jpg", "/products/traworld/40709518/2.jpg", "/products/traworld/40709518/3.jpg", "/products/traworld/40709518/4.jpg", "/products/traworld/40709518/5.jpg", "/products/traworld/40709518/6.jpg"]'::jsonb,
  '[{"name": "Red", "code": "#1a1a1a", "images": ["/products/traworld/40709518/1.jpg", "/products/traworld/40709518/2.jpg", "/products/traworld/40709518/3.jpg", "/products/traworld/40709518/4.jpg", "/products/traworld/40709518/5.jpg", "/products/traworld/40709518/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Polypropylene 360-Degree Rotation Padded Trolley Bag", "SKU": "TRW-40709518", "Material": "Durable High-Grade Polypropylene / Polycarbonate", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-polypropylene-360-degree-rotation-padded-trolley-bag/40709518/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709507',
  'traworld-40709507-traworld-set-of-3-360-degree-rotation-padded-trolley-bag',
  'TRAWORLD Set Of 3 360-Degree Rotation Padded Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Set Of 3 360-Degree Rotation Padded Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  24996,
  24996,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709507/1.jpg',
  '["/products/traworld/40709507/1.jpg", "/products/traworld/40709507/2.jpg", "/products/traworld/40709507/3.jpg", "/products/traworld/40709507/4.jpg", "/products/traworld/40709507/5.jpg", "/products/traworld/40709507/6.jpg"]'::jsonb,
  '[{"name": "Red", "code": "#1a1a1a", "images": ["/products/traworld/40709507/1.jpg", "/products/traworld/40709507/2.jpg", "/products/traworld/40709507/3.jpg", "/products/traworld/40709507/4.jpg", "/products/traworld/40709507/5.jpg", "/products/traworld/40709507/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Set Of 3 360-Degree Rotation Padded Trolley Bag", "SKU": "TRW-40709507", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "8-Wheel 360-Degree Silent Rotation Spinner Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-set-of-3-360-degree-rotation-padded-trolley-bag/40709507/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709523',
  'traworld-40709523-traworld-textured-hard-sided-water-resistant-medium-trolley-bag',
  'TRAWORLD Textured Hard-Sided Water-Resistant Medium Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Textured Hard-Sided Water-Resistant Medium Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  9599,
  9599,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709523/1.jpg',
  '["/products/traworld/40709523/1.jpg", "/products/traworld/40709523/2.jpg", "/products/traworld/40709523/3.jpg", "/products/traworld/40709523/4.jpg", "/products/traworld/40709523/5.jpg", "/products/traworld/40709523/6.jpg"]'::jsonb,
  '[{"name": "Black", "code": "#1a1a1a", "images": ["/products/traworld/40709523/1.jpg", "/products/traworld/40709523/2.jpg", "/products/traworld/40709523/3.jpg", "/products/traworld/40709523/4.jpg", "/products/traworld/40709523/5.jpg", "/products/traworld/40709523/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Textured Hard-Sided Water-Resistant Medium Trolley Bag", "SKU": "TRW-40709523", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "360-Degree Multi-Directional Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-textured-hard-sided-water-resistant-medium-trolley-bag/40709523/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709516',
  'traworld-40709516-traworld-textured-hard-sided-water-resistant-cabin-trolley-bag',
  'TRAWORLD Textured Hard-Sided Water-Resistant Cabin Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Textured Hard-Sided Water-Resistant Cabin Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  7549,
  7549,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709516/1.jpg',
  '["/products/traworld/40709516/1.jpg", "/products/traworld/40709516/2.jpg", "/products/traworld/40709516/3.jpg", "/products/traworld/40709516/4.jpg", "/products/traworld/40709516/5.jpg", "/products/traworld/40709516/6.jpg"]'::jsonb,
  '[{"name": "Black", "code": "#1a1a1a", "images": ["/products/traworld/40709516/1.jpg", "/products/traworld/40709516/2.jpg", "/products/traworld/40709516/3.jpg", "/products/traworld/40709516/4.jpg", "/products/traworld/40709516/5.jpg", "/products/traworld/40709516/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Textured Hard-Sided Water-Resistant Cabin Trolley Bag", "SKU": "TRW-40709516", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "360-Degree Multi-Directional Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-textured-hard-sided-water-resistant-cabin-trolley-bag/40709516/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709519',
  'traworld-40709519-traworld-textured-hard-sided-water-resistant-medium-trolley-bag',
  'TRAWORLD Textured Hard-Sided Water-Resistant Medium Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Textured Hard-Sided Water-Resistant Medium Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  9599,
  9599,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709519/1.jpg',
  '["/products/traworld/40709519/1.jpg", "/products/traworld/40709519/2.jpg", "/products/traworld/40709519/3.jpg", "/products/traworld/40709519/4.jpg", "/products/traworld/40709519/5.jpg", "/products/traworld/40709519/6.jpg"]'::jsonb,
  '[{"name": "Pink", "code": "#1a1a1a", "images": ["/products/traworld/40709519/1.jpg", "/products/traworld/40709519/2.jpg", "/products/traworld/40709519/3.jpg", "/products/traworld/40709519/4.jpg", "/products/traworld/40709519/5.jpg", "/products/traworld/40709519/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Textured Hard-Sided Water-Resistant Medium Trolley Bag", "SKU": "TRW-40709519", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "360-Degree Multi-Directional Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-textured-hard-sided-water-resistant-medium-trolley-bag/40709519/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709531',
  'traworld-40709531-traworld-textured-hard-sided-water-resistant-cabin-trolley-bag',
  'TRAWORLD Textured Hard-Sided Water-Resistant Cabin Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Textured Hard-Sided Water-Resistant Cabin Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  7549,
  7549,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709531/1.jpg',
  '["/products/traworld/40709531/1.jpg", "/products/traworld/40709531/2.jpg", "/products/traworld/40709531/3.jpg", "/products/traworld/40709531/4.jpg", "/products/traworld/40709531/5.jpg", "/products/traworld/40709531/6.jpg"]'::jsonb,
  '[{"name": "Blue", "code": "#1a1a1a", "images": ["/products/traworld/40709531/1.jpg", "/products/traworld/40709531/2.jpg", "/products/traworld/40709531/3.jpg", "/products/traworld/40709531/4.jpg", "/products/traworld/40709531/5.jpg", "/products/traworld/40709531/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Textured Hard-Sided Water-Resistant Cabin Trolley Bag", "SKU": "TRW-40709531", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "360-Degree Multi-Directional Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-textured-hard-sided-water-resistant-cabin-trolley-bag/40709531/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709524',
  'traworld-40709524-traworld-textured-hard-sided-water-resistant-cabin-trolley-bag',
  'TRAWORLD Textured Hard-Sided Water-Resistant Cabin Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Textured Hard-Sided Water-Resistant Cabin Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  7549,
  7549,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709524/1.jpg',
  '["/products/traworld/40709524/1.jpg", "/products/traworld/40709524/2.jpg", "/products/traworld/40709524/3.jpg", "/products/traworld/40709524/4.jpg", "/products/traworld/40709524/5.jpg", "/products/traworld/40709524/6.jpg"]'::jsonb,
  '[{"name": "Pink", "code": "#1a1a1a", "images": ["/products/traworld/40709524/1.jpg", "/products/traworld/40709524/2.jpg", "/products/traworld/40709524/3.jpg", "/products/traworld/40709524/4.jpg", "/products/traworld/40709524/5.jpg", "/products/traworld/40709524/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Textured Hard-Sided Water-Resistant Cabin Trolley Bag", "SKU": "TRW-40709524", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "360-Degree Multi-Directional Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-textured-hard-sided-water-resistant-cabin-trolley-bag/40709524/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709537',
  'traworld-40709537-traworld-textured-hard-sided-water-resistant-cabin-trolley-bag',
  'TRAWORLD Textured Hard-Sided Water-Resistant Cabin Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Textured Hard-Sided Water-Resistant Cabin Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  7549,
  7549,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709537/1.jpg',
  '["/products/traworld/40709537/1.jpg", "/products/traworld/40709537/2.jpg", "/products/traworld/40709537/3.jpg", "/products/traworld/40709537/4.jpg", "/products/traworld/40709537/5.jpg", "/products/traworld/40709537/6.jpg"]'::jsonb,
  '[{"name": "Brown", "code": "#1a1a1a", "images": ["/products/traworld/40709537/1.jpg", "/products/traworld/40709537/2.jpg", "/products/traworld/40709537/3.jpg", "/products/traworld/40709537/4.jpg", "/products/traworld/40709537/5.jpg", "/products/traworld/40709537/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Textured Hard-Sided Water-Resistant Cabin Trolley Bag", "SKU": "TRW-40709537", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "360-Degree Multi-Directional Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-textured-hard-sided-water-resistant-cabin-trolley-bag/40709537/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709551',
  'traworld-40709551-traworld-textured-hard-sided-water-resistant-medium-trolley-bag',
  'TRAWORLD Textured Hard-Sided Water-Resistant Medium Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Textured Hard-Sided Water-Resistant Medium Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  9599,
  9599,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709551/1.jpg',
  '["/products/traworld/40709551/1.jpg", "/products/traworld/40709551/2.jpg", "/products/traworld/40709551/3.jpg", "/products/traworld/40709551/4.jpg", "/products/traworld/40709551/5.jpg", "/products/traworld/40709551/6.jpg"]'::jsonb,
  '[{"name": "Blue", "code": "#1a1a1a", "images": ["/products/traworld/40709551/1.jpg", "/products/traworld/40709551/2.jpg", "/products/traworld/40709551/3.jpg", "/products/traworld/40709551/4.jpg", "/products/traworld/40709551/5.jpg", "/products/traworld/40709551/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Textured Hard-Sided Water-Resistant Medium Trolley Bag", "SKU": "TRW-40709551", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "360-Degree Multi-Directional Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-textured-hard-sided-water-resistant-medium-trolley-bag/40709551/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

INSERT INTO products (
  id, sku, slug, name, description, price, original_price, category_id,
  image, images, colors, features, specifications, rating, review_count,
  stock, is_new, is_highlighted, is_premium, gender, sub_category, myntra_url, is_active
) VALUES (
  uuid_generate_v4(),
  'TRW-40709510',
  'traworld-40709510-traworld-textured-hard-sided-water-resistant-medium-trolley-bag',
  'TRAWORLD Textured Hard-Sided Water-Resistant Medium Trolley Bag',
  'Experience seamless luxury travel with TRAWORLD Textured Hard-Sided Water-Resistant Medium Trolley Bag. Engineered with an ultra-durable lightweight shell, smooth 360-degree spinner wheels, and ergonomic telescopic trolley handle.',
  9599,
  9599,
  (SELECT id FROM categories WHERE slug = 'luggage' LIMIT 1),
  '/products/traworld/40709510/1.jpg',
  '["/products/traworld/40709510/1.jpg", "/products/traworld/40709510/2.jpg", "/products/traworld/40709510/3.jpg", "/products/traworld/40709510/4.jpg", "/products/traworld/40709510/5.jpg", "/products/traworld/40709510/6.jpg"]'::jsonb,
  '[{"name": "Blue", "code": "#1a1a1a", "images": ["/products/traworld/40709510/1.jpg", "/products/traworld/40709510/2.jpg", "/products/traworld/40709510/3.jpg", "/products/traworld/40709510/4.jpg", "/products/traworld/40709510/5.jpg", "/products/traworld/40709510/6.jpg"]}]'::jsonb,
  '["Unbreakable lightweight impact-resistant shell with scratch-resistant texture", "360-degree silent multi-directional 8-wheel spinner system for effortless glide", "Integrated recessed TSA-approved combination lock for secure international travel", "Spacious interior with zippered divider, tie-down compression straps & mesh pockets"]'::jsonb,
  '{"Brand": "TRAWORLD", "Model": "TRAWORLD Textured Hard-Sided Water-Resistant Medium Trolley Bag", "SKU": "TRW-40709510", "Material": "Premium Hard-Sided ABS", "Warranty": "3 Years International Manufacturer Warranty", "Closure": "TSA Combination Lock / Premium Heavy-Duty Zipper", "Wheels": "360-Degree Multi-Directional Wheels", "Water Resistance": "Yes", "Country of Origin": "India"}'::jsonb,
  4.6,
  12,
  35,
  true,
  false,
  true,
  'unisex',
  'trolley-bags',
  'https://www.myntra.com/trolley-bag/traworld/traworld-textured-hard-sided-water-resistant-medium-trolley-bag/40709510/buy',
  true
) ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  category_id = EXCLUDED.category_id,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  colors = EXCLUDED.colors,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  sub_category = EXCLUDED.sub_category,
  is_premium = true,
  gender = EXCLUDED.gender,
  myntra_url = EXCLUDED.myntra_url,
  is_active = true,
  updated_at = NOW();

